public class class_main {
	public static void main(String[] args) {
		Kotak kotakHitam = new Kotak();
		kotakHitam.setPanjang(20);
		kotakHitam.setLebar(10);
		kotakHitam.hitungLuas();
		kotakHitam.hitungKeliling();
			System.out.println("Panjang : " + kotakHitam.getPanjang());
			System.out.println("Lebar : " + kotakHitam.getLebar());
			System.out.println("LuasKotak : " + kotakHitam.getLuas());
			System.out.println("KelilingKotak " + kotakHitam.getKeliling());
			System.out.println("___________________________________________");
			//Hasil Mahasiswa
			Mahasiswa mhs1 = new Mahasiswa();
			mhs1.setNama("Husnul Fahmi");
			mhs1.setNim("D0217365");
			mhs1.setAlamat("Pangkajene");
			mhs1.setGolonganDarah("AB");
			mhs1.setStatus("Mahasiswa");
			mhs1.setTinggiBadan(165);
			mhs1.setBeratBadan(49);
			System.out.println("Nama : " + mhs1.getNama());
			System.out.println("Nim : " + mhs1.getNim());
			System.out.println("Alamat : " + mhs1.getAlamat());
			System.out.println("GolonganDarah : " + mhs1.getGolonganDarah());
			System.out.println("Status : " + mhs1.getStatus());
			System.out.println("TinggiBadan : " + mhs1.getTinggiBadan());
			System.out.println("BeratBadan : " + mhs1.getBaratBadan());
			System.out.println("---------------------------------------------");
			System.out.println("------Object Kelas node------");
			//membuat object darikelas node
			node node = new node();
			//method setter node
			node.label = "MILO";
			node.Value = 1;
			//method getter node
			System.out.println("Nama Label : " + node.getlabel());
			System.out.println("jumlah label : " + node.getValue());
			//membuat object darikelas stack
			stack stack = new stack();
			System.out.println("------Object Kelas stack------");
			stack.value[0] = "fahmi";
			stack.value[1] = "ali";
			stack.value[2] = "kumala";
			stack.value[3] = "sari";
			stack.value[4] = "intan";
			stack.value[5] = "berlian";
			stack.value[6] = "aby";
			stack.value[7] = "laptop";
			stack.value[8] = "pensil";
			stack.value[9] = "penghapus";
			stack.value[10] = "spidol";
			stack.value[11] = "cas";
			stack.value[12] = "tombol";
			stack.value[13] = "power";
			stack.value[14] = "on";
			stack.value[15] = "of";
			stack.value[16] = "fof";
			stack.value[17] = "asli";
			stack.value[18] = "palsu";
			stack.value[19] = "lembar";
			stack.value[20] = "joy";
			stack.value[21] = "rey";
			stack.value[22] = "juy";
			stack.value[23] = "jin";
			stack.value[24] = "malaikat";
			stack.value[25] = "maba";
			stack.value[26] = "senior";
			stack.value[27] = "teknik";
			stack.value[28] = "fisip";
			stack.value[29] = "ekonomi";
			stack.value[30] = "faperkan";
			stack.value[31] = "akutansi";
			stack.value[32] = "dokter";
			stack.value[33] = "insiyur";
			stack.value[34] = "tukan batu";
			stack.value[35] = "guru";
			stack.value[36] = "bupari";
			stack.value[37] = "bupati";
			stack.value[38] = "bukalapak";
			stack.value[39] = "jd.id";
			stack.value[40] = "Buk";
			stack.value[41] = "Book";
			stack.value[42] = "pen";
			stack.value[43] = "stor";
			stack.value[44] = "stur";
			stack.value[45] = "dor";
			stack.value[46] = "dir";
			stack.value[47] = "pak";
			stack.value[48] = "sugi";
			stack.value[49] = "kerja";
			stack.value[50] = "coding";
			stack.value[51] = "malam";
			stack.value[52] = "dingin";
			stack.value[53] = "sambil";
			stack.value[54] = "minum";
			stack.value[55] = "kopi";
			stack.value[56] = "hitam";
			stack.value[57] = "di";
			stack.value[58] = "bawa";
			stack.value[59] = "rembulan";
			stack.value[60] = "yng";
			stack.value[61] = "terang";
			stack.value[62] = "dan";
			stack.value[63] = "di";
			stack.value[64] = "temani";
			stack.value[65] = "suara";
			stack.value[66] = "hantu";
			stack.value[67] = "yang";
			stack.value[68] = "bergema";
			stack.value[69] = "di";
			stack.value[70] = "alam";
			stack.value[71] = "mimpi";
			stack.value[72] = "kemudian";
			stack.value[73] = "terbangun";
			stack.value[74] = "dari";
			stack.value[75] = "mimpi";
			stack.value[76] = "dan";
			stack.value[77] = "ke";
			stack.value[78] = "kamar";
			stack.value[79] = "mandi";
			stack.value[80] = "untuk";
			stack.value[81] = "membasu";
			stack.value[82] = "wajah";
			stack.value[83] = "yang";
			stack.value[84] = "tampan";
			stack.value[85] = "tapi";
			stack.value[86] = "dikaca";
			stack.value[87] = "liat";
			stack.value[88] = "tambah";
			stack.value[89] = "tanpan";
			stack.value[90] = "yyy";
			stack.value[91] = "ggg";
			stack.value[92] = "sari";
			stack.value[93] = "bunga";
			stack.value[94] = "kemala";
			stack.value[95] = "sari";
			stack.value[96] = "bintang";
			stack.value[97] = "tinggi";
			stack.value[98] = "yang";
			stack.value[99] = "kecil";
			for(int i=0;i <stack.value.length;i++){System.out.println(stack.value[i]);};
}
	}
